#     ___       __          __            ___
#    /   |     / /    _____/ /___  ______/ (_)___  _____
#   / /| |__  / /    / ___/ __/ / / / __  / / __ \/ ___/
#  / ___ / /_/ /    (__  ) /_/ /_/ / /_/ / / /_/ (__  )
# /_/  |_\____/    /____/\__/\__,_/\__,_/_/\____/____/


#      check our discord: https://discord.io/AJstudios
#      check our github: https://github.com/AJstudiosit
#      you can see this project on https://github.com/AJstudiosit/wdyc-plugin


# >>> CUSTOM MESSAGES
# PLACEHOLDERS: (the allowed placeholders are specified next to the string)
# %staffer% returns the name of the staffer/player that controlled/reported.
# %player% returns the name of the specified player in the command.
# %server% returns the name of the server of a player.
# %reason% returns the reason of a report

# Who use the command isn't a player (console)
not_a_player: 'This command can only be used by a player'
# Who use the command hasn't the permission to use the command
not_perms: 'You don''t have any permission for perform this command'
# Too many args
too_args: 'Too many args in this command!'
# Not enough args
minus_args: 'Not enough args in this command!'
# Player not specified
ss_player_not_specified: 'You didn''t specify a player to control.' # %staffer%
# Player not specified
report_player_not_specified: 'You didn''t specify a player to report.' # %staffer%
# Specified player is not online
not_online: 'Specified player isn''t online' # %staffer%
# SS usage
ss_usage: 'Usage: /ss <player>'
# ENDSS usage
endss_usage: 'Usage: /endss <player>'
# SS usage
report_usage: 'Usage: /report <player> <motivo>'

# In what server do you have to send the player and the staff when the control START?
server_ss: 'control'
# In what server do you have to send the player and the staff when the control END?
server_finish: 'hub'
    
# Message to send when a player start the ss
player_join_ss: 'That''s a ss! Do not logout and follow the instructions of the staff' # %staffer% %player%
# Message to send when a player left the ss
player_left_ss: 'Your clean! bb!' # %staffer% %player%

# Message to send when a player start the ss
staff_join_ss: 'Hi sir, now you can control %player%' # %staffer% %player%
# Message to send when a player left the ss
staff_left_ss: 'Control ended successfully' # %staffer% %player%

# Message to send if the player is immune from ss
ss_immunity: 'This player is immune from ss!' # %staffer% %player%
# Should we send a message when a player goes into ss? (True/False)
ss_sendGlobalMsg: true
# Global message
ss_globalMsg: '%player% was getting controlled by %staffer%.' # %staffer% %player%

# Message to send when the report is successfully sent
successfully_report: '%player% reported successfully' # %staffer% %player%
# Message to send if the player is immune from report
immunity: 'This player is immune from report!' # %staffer% %player%
# Message to send to the staff when a player report someone
# use \n for go to newline
staff_msg: 'REPORT \n By: %sender% \n To: %player% \n On: %server% \n For: %reason%' # %staffer% %player% %server% %reason%

permissions_to_remove_when_starting_ss: 'bungeecord.command.server,test.permission.aj' # ALWAYS follow this setup: permission,permission,*